---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: axonetiq/user-service:latest
          env:
            - name: DB_HOST
              value: 'localhost'
            - name: BRANCH_STATION_SVC_URL
              value: 'branch-station-svc.wap4-production.svc.cluster.local'
            - name: CONTACT_SVC_URL
              value: 'contact-svc.wap4-production.svc.cluster.local'
            - name: MASTER_DATA_SVC_URL
              value: 'master-data-svc.wap4-production.svc.cluster.local'
            - name: INSURANCE_SVC_URL
              value: 'insurance-svc.wap4-production.svc.cluster.local'
            - name: DB_NAME
              value: 'pdr_user_svc'
            - name: DB_USER
              value: 'root'
            - name: DB_PASS
              value: 'password'
            - name: DB_DIALECT
              value: 'mysql'
            - name: DB_VERSION
              value: '5.5'
          ports:
            - containerPort: 8080